Weather/Controllers/AnaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Weather.Controllers
{
    public class AnaController : Controller
    {
        // GET: Ana
        public ActionResult WeatherJS()
        {
            return View();
        }
    }
}

Weather/Views/Ana/WeatherJS.cshtml
@{
    ViewBag.Title = "WeatherJS";
}

<h2>WeatherJS</h2>

<p id="name"> </p>
<p id="temp"> </p>
<p id="humidity"></p>
<p id="description"> </p>
<p id="country"></p>

<input type="button" name="button" id="selam" value="Ekle">
<input type="text" name="text1" id="text1" value="şehir girin"><br>
<input type="button" name="button" id="geri" value="geri">
<input type="button" name="button" id="ileri" value="ileri">
<script>
    var country = [];
    var btnSelam = document.getElementById("selam");
    var btnText = document.getElementById("text1");
    btnSelam.onclick = function () {
        
        country.push(btnText.value);
        console.log(country);
        document.getElementById("country").innerHTML ="İller: " + country;
    }
    

</script>

<button>Sıcaklık Al</button>
<script>
    var array = [];
    var kelime;
    var bla;
    var sayac = 0;
    var sehir = 0;
    $("#geri").hide(100);
    $("#ileri").hide(100);
    $(document).ready(function(){
        $("button").click(function () {
            array = [];
            sayac = 0;
            console.log("girdim");
            console.log(" hey " + array);
            country.forEach(function (entry) {
                $("#geri").show(100);
                $("#ileri").show(100);
                kelime = "http://api.openweathermap.org/data/2.5/weather?q="
                kelime = kelime.concat(entry + "&APPID=d78faac163cbac500bcf96a76eed82d0&units=imperial");
               
                $.get(kelime, function (response) {
                    if (array.lenght == country.length)
                        array = [];
                  array.push(response.name);
                  response.weather.forEach(function (entry1) {
                      array[sayac]= array[sayac].concat(" " +  response.main.temp + " " + response.main.humidity + " " + entry1.description);
                  });
                  console.log(response);
                  sayac++;
                });
                
            }); 
            console.log(array);
            console.log(country);   
        });
        
    });
    var btngeri = document.getElementById("geri");
    var btnileri = document.getElementById("ileri");
    btngeri.onclick = function () {
        if (sehir > 0) {
            sehir--;
            bla = array[sehir].split(" ");
            document.getElementById("description").innerHTML = "";
            document.getElementById("name").innerHTML = bla[0];
            document.getElementById("temp").innerHTML = bla[1];
            document.getElementById("humidity").innerHTML = bla[2];
            for (var i = 3; i < bla.length; i++) {
                document.getElementById("description").innerHTML += bla[i];
            }
        }
       
    }
    btnileri.onclick = function () {
        if (sehir < array.length-1 )  {
            sehir++;
            bla= array[sehir].split(" ");
            document.getElementById("description").innerHTML = "";
            document.getElementById("name").innerHTML = bla[0] ;
            document.getElementById("temp").innerHTML = bla[1] + " F derece" ;
            document.getElementById("humidity").innerHTML = bla[2] + " Nem oranı";
            for (var i = 3; i < bla.length; i++) {
            document.getElementById("description").innerHTML += bla[i] +" " ;
            }
            
        }

    }
    var saniye = 20;
    function bak() {
        if (saniye > 0) saniye = saniye - 1;
        else {
            saniye = 20;
            console.log("10 saniye oldu");
            $("button").click();
            
        }
    }
    $(document).ready(function () {
        setInterval(bak, 1000);
    });
</script>

Weather/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
    <script src="~/Scripts/jquery-3.2.1.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "WeatherJS", "Ana", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>